// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  api: ['intro'],
  docs: ['intro'],
  mobile: ['intro'],
  portal: [{ type: 'autogenerated', dirName: '.' }],
  website: ['intro'],
};

module.exports = sidebars;
